name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} Rails ${{ matrix.rails_version }}
    strategy:
      matrix:
        ruby:
          - '3.0.6'
          - '3.1.4'
          - '3.2.2'
        rails_version:
          - '6.0'
          - '6.1'
          - '7.0'
          - '7.1'
    env:
      RAILS_VERSION: ${{ matrix.rails_version }}
    steps:
    - uses: actions/checkout@v2
    - name: Remove Gemfile.lock for CI
      run: rm Gemfile.lock
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: |
        bundle exec rbs collection update
        bundle exec rake
